spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/myBookshelf
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: oauth
  session:
    store-type: jdbc

logging:
  level:
    org.hibernate.SQL: debug