spring:
  profiles:
    active: default
    include: oauth
  session:
    store-type: jdbc

logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  profiles: real
    include: [oauth, real-db]
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc