spring:
  profiles:
    active: local

---

spring:
  profiles: local
  profiles.include: oauth
  session:
    store-type: jdbc

logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  profiles: real
  profiles.include: oauth, real-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc