spring:
  profiles:
    active: local

---

spring:
  profiles: local
  profiles.include: oauth, api
  session:
    store-type: jdbc
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa_ch2;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  properties:
    hibernate:
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  profiles: real
  profiles.include: oauth, real-db, api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc